### ISSUE TITLE
Exception starting VS2010 since a few versions

### ISSUE THREAD

**Issue by MartinL0815** [ashmind/ExceptionBreaker#9]
![Screenshot from Exception while VS2010 starting up](https://farm8.staticflickr.com/7596/16737460066_91fde87053.jpg)

The dialog above comes up, everytime I start VS2010!
It doesn't matter if I press yes or no, the ActivityLog XML file won't be written, so I have nothing to help you to fix this, but the screenshot above.
If I do not react onto this dialog, VS2010 crashes silently and does not complete its startup.

**Comment by ashmind** [comment]
@MartinL0815 Thanks for reporting this!

Did you run VS with `/log` command line argument? I think it is required for it to write the `ActivityLog`.

**Comment by MartinL0815** [comment]
No, I never did before.

Even VS2013 I never started with `/log`, but it did create the ActivityLog.xml file on extension errors, exceptions.

I'll try out!

**Comment by MartinL0815** [comment]
Here the extract of the ActivityLog.xml file:

```xml
<?xml-stylesheet type="text/xsl" href="ActivityLog.xsl"?>
<activity>
  <entry>
    <record>440</record>
    <time>2015/03/09 17:31:20.793</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
    <guid>{A83E8A33-E775-4A79-BE41-EFE20007EEBD}</guid>
  </entry>
  <entry>
    <record>441</record>
    <time>2015/03/09 17:31:20.794</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [ExceptionBreaker.ExceptionBreakerPackage, ExceptionBreaker, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null]</description>
    <guid>{A83E8A33-E775-4A79-BE41-EFE20007EEBD}</guid>
  </entry>
  <entry>
    <record>442</record>
    <time>2015/03/09 17:31:20.799</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [ExceptionBreaker.ExceptionBreakerPackage, ExceptionBreaker, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null]</description>
    <guid>{A83E8A33-E775-4A79-BE41-EFE20007EEBD}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo>Object reference not set to an instance of an object.</errorinfo>
  </entry>
  <entry>
    <record>443</record>
    <time>2015/03/09 17:31:20.801</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [ExceptionBreaker.ExceptionBreakerPackage, ExceptionBreaker, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null]</description>
    <guid>{A83E8A33-E775-4A79-BE41-EFE20007EEBD}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo>Object reference not set to an instance of an object.</errorinfo>
  </entry>
</activity>
```

**Comment by ashmind** [comment]
Can you try the following?
```
reg query HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\10.0\ExtensionManager\EnabledExtensions /f "a83e8a33-e775-4a79-be41-efe20007eebd"
```

And see if the path actually exists on your disk?

If it does, than it might be an error in the extension itself -- I'll take a look at getting better logging in as soon as I have time.

**Comment by MartinL0815** [comment]
Here the result of the registry query:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

c:\windows\system32>reg query HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\10.0\ExtensionManager\EnabledExtensions /f "a83e8a33-e775-4a79-be41-efe20007eebd"

HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\10.0\ExtensionManager\EnabledExtensions
    a83e8a33-e775-4a79-be41-efe20007eebd,1.1.1    REG_SZ    C:\Users\lemburg\AppData\Local\Microsoft\VisualStudio\10.0\Extensions\Andrey Shchekin\Exception Breaker\1.1.1\

End of search: 1 match(es) found.

c:\windows\system32>
```

**Comment by ashmind** [comment]
@MartinL0815 Thanks! Can you check that `C:\Users\lemburg\AppData\Local\Microsoft\VisualStudio\10.0\Extensions\Andrey Shchekin\Exception Breaker\1.1.1\` actually exists on your machine?

**Comment by MartinL0815** [comment]
Here a screenshot from the explorer:

![Explorer Screenshot](https://cloud.githubusercontent.com/assets/525700/6593474/5bdafefc-c7d9-11e4-9908-1bd542479f3e.png)

**Comment by pjquirk** [comment]
I'm also seeing this issue in VS2010, using v1.1.1.   Are there any other diagnostics I can provide?  Any progress on a fix?

**Comment by ashmind** [comment]
@pjquirk Unfortunately I wasn't able to find the cause and didn't have additional time to dedicate to it.
I'll take another look.

Can you please provide your ActivityLog?

If you have VS SDK installed, you can try running extension from source to see it fails on any exception on startup.

**Comment by pjquirk** [comment]
I attached WinDbg to VS2010 on launch and [created a gist](https://gist.github.com/pjquirk/9a268dd10fe7f9cad743) with the exception details.  It is a `NullReferenceException` in `Microsoft.VisualStudio.Shell.Package.GetOutputPane`, though it's not clear to me why...  

Here's the relevant bits from my ActivityLog as well:

	<entry>
		<record>496</record>
		<time>2015/07/27 03:24:37.054</time>
		<type>Information</type>
		<source>VisualStudio</source>
		<description>Begin package load [ExceptionBreaker.ExceptionBreakerPackage, ExceptionBreaker, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null]</description>
		<guid>{A83E8A33-E775-4A79-BE41-EFE20007EEBD}</guid>
	</entry>
	<entry>
		<record>497</record>
		<time>2015/07/27 03:24:37.063</time>
		<type>Error</type>
		<source>VisualStudio</source>
		<description>SetSite failed for package [ExceptionBreaker.ExceptionBreakerPackage, ExceptionBreaker, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null]</description>
		<guid>{A83E8A33-E775-4A79-BE41-EFE20007EEBD}</guid>
		<hr>80004003 - E_POINTER</hr>
		<errorinfo>Object reference not set to an instance of an object.</errorinfo>
	</entry>
	<entry>
		<record>498</record>
		<time>2015/07/27 03:24:37.064</time>
		<type>Error</type>
		<source>VisualStudio</source>
		<description>End package load [ExceptionBreaker.ExceptionBreakerPackage, ExceptionBreaker, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null]</description>
		<guid>{A83E8A33-E775-4A79-BE41-EFE20007EEBD}</guid>
		<hr>80004003 - E_POINTER</hr>
		<errorinfo>Object reference not set to an instance of an object.</errorinfo>
	</entry>

**Comment by ashmind** [comment]
@pjquirk This is great -- I definitely remember doing a workaround for that in some other extension. I'll take a look later today. Thanks!

**Comment by ashmind** [comment]
@pjquirk Can you test if it still happens when you install  https://github.com/ashmind/ExceptionBreaker/releases/tag/v1.1.2-test-1 (manually)?

**Comment by pjquirk** [comment]
That works for me!  I played around with it a bit, trying different configurations and restarting VS and I never saw the error.  Plus, I do see the logging in the output window.  Thanks for spending time to help support us stuck on old versions of VS!

**Comment by iobus** [comment]
I was having this problem as well.  That update fixed it for me too.  Thanks!

**Comment by ashmind** [comment]
Great! I'm going to release it through Gallery today or tomorrow then.
Thanks @pjquirk for the research.
